// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcteshwffozlkyqybmwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdGVzaHdmZm96bGt5cXlibXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTgxMTAsImV4cCI6MjA1ODM5NDExMH0.tO-ldDs6exHiX7PkfHW9Zvxow60m3NcweBZt7puUGdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);